### ISSUE TITLE
Peer & Peer Code Review 25/04/2023

### ISSUE THREAD

**Issue by sunga12** [lordksix/BooksApp#3]
- Live Demo link is not working, it would be good to fix it.
- It would be a good practice to add the required attribute to your HTML file as well as the JS
- Rest of the Code is quite good!

**Comment by lordksix** [comment]
Thank you. 
- Live Demo typo fixed
- required added
https://github.com/lordksix/BooksApp/blob/c1a4f0b49ff0f03dbc4d3bcd00de0c6e3a2f530e/index.html#L20-L24
