### ISSUE TITLE
code review for the project

### ISSUE THREAD

**Issue by kerlos-bahaa** [lordksix/BooksApp#5]
- your code was done nicely and cleanly so good job so far but I noticed something with  `nav` that inside the header its better to not use it sometimes and at times you need to get the `logo` out of it  other than that you did a splendid job

**Comment by lordksix** [comment]
@kerlos-bahaa  Thank you for the words, and the suggestions, and for taking the time to check my code. You can always follow my profile.
I will take under advisement your suggestions, however, the idea behind the decision to code it in that position was that there is always a link in the logo or title, and there would be a link there, and such it is part of the `nav`.
